Patso
roug11/movie-reservation-system pull request #20
Opened 2024-06-12 16:35 UTC by davidpatsina

2024-06-12 16:53 UTC, roug11 requested changes

2024-06-12 16:53 UTC, roug11 commented on Theatre/src/main/java/com/example/theatre/service/TheatreService.java
> +            currentTheatre = TheatreRequestDto.builder()
ბილდერი თვითონ ქმნის ახალ ობიექტს, ამიტომ არ უნდა new, 35 ხაზზე რაც გიწერია ეგ პირდაპირ გაუტოლე ცვლადს

2024-06-12 16:53 UTC, roug11 commented on Theatre/src/main/resources/application.properties
> +spring.datasource.password=rootroot
ბაზის იუზერი და პაროლი არ ემთხვევა დოკერის ბაზისას და ლოკალურად უშვებ სერვერს და მაგას უქონექთდები რატოა სხვა?

2024-06-12 16:53 UTC, roug11 commented on Theatre/src/main/java/com/example/theatre/api/controller/TheatreController.java
> +    }
ეს აღარ გვჭირდება წასაშლელია

2024-06-12 16:53 UTC, roug11 commented on Theatre/src/main/java/com/example/theatre/persistence/entity/Theatre.java
> +//@SequenceGenerator(name = "theater_seq", sequenceName = "theater_seq", allocationSize = 1)
სიქუენსი არ გვაქ ბაზაში და ეს კომენტარი არ გვჭირდება

2024-06-12 16:53 UTC, roug11 commented on Theatre/src/main/java/com/example/theatre/service/TheatreService.java
> +    public TheatreService(TheatreRepository theatreRepository) {
ეს ინჯექთიც ისე ქენი როგორც TheatreController-ში გიწერია.

2024-06-12 16:58 UTC, davidpatsina commented on Theatre/src/main/resources/application.properties
> +spring.datasource.password=rootroot
არ ვიცი დოკერი არ გამომოყენებია ჩემს ლეპტოპში იყო ბაზა გაშვებული

2024-06-12 17:01 UTC, davidpatsina commented on Theatre/src/main/java/com/example/theatre/api/controller/TheatreController.java
> +    }
ეს მთლიანად კონტროლერი თუ sayHello ?

2024-06-13 20:11 UTC, gkhelo requested changes

2024-06-13 20:11 UTC, gkhelo commented on Theatre/pom.xml
> +        </dependency>
ეს dependency ორჯერაა დამატებული, შეგიძლია წაშალო.

2024-06-13 20:11 UTC, gkhelo commented on Theatre/src/main/java/com/example/theatre/api/controller/TheatreController.java
> +    }
sayHello მეთოდი წაშალე მარტო.

2024-06-13 20:11 UTC, gkhelo commented on Theatre/src/main/java/com/example/theatre/api/controller/TheatreController.java
> +@RequiredArgsConstructor
ეს ანოტაცია მგონი არაა საჭირო.

2024-06-13 20:11 UTC, gkhelo commented on Theatre/src/main/java/com/example/theatre/api/dto/TheatreRequestDto.java
> +    }
@getter ანოტაცია შეგიძლია გამოიყენო.

2024-06-13 20:11 UTC, gkhelo commented on Theatre/src/main/java/com/example/theatre/model/TheatreModel.java
> +public class TheatreModel {
ამ კლასს არ იყენებ არსად, შეგიძლია წაშალო.

2024-06-13 20:11 UTC, gkhelo commented on Theatre/src/main/java/com/example/theatre/service/TheatreService.java
> +public class TheatreService {
სერვისმა ჯობია Theatre დააბრუნოს და კონტროლერში შეგიძლია დამეპო DTO-ში.

2024-06-13 20:11 UTC, gkhelo commented on Theatre/src/main/java/com/example/theatre/api/dto/TheatreRequestDto.java
> +public class TheatreRequestDto {
TheaterDto ჯობია ერქვას კლასს.

2024-06-13 20:11 UTC, gkhelo commented on Theatre/src/main/java/com/example/theatre/api/controller/TheatreController.java
> +    public TheatreRequestDto getById(@PathVariable("theatreid") int theatreid){
ჯავაში camelCase უნდა გამოიყენო ხოლმე ცვლადების სახელებზე: theatreId

2024-06-15 09:19 UTC, davidpatsina commented
....

2024-06-15 09:20 UTC, closed without merging